### PR TITLE
ENH: Update Python CI for ITK v5.2.0.post2

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Comment by tbirdso** [comment]
@thewtex @dzenanz

**Review by dzenanz — APPROVED** [review]
Update Python version number in `setup.py`.

**Comment by thewtex** [comment]
>Update Python version number in setup.py.

Yes, please do this in future updates. The package version and the `itk` dependency version.

To keep things moving, I will add this and tag as a follow-up.

**Review by thewtex — APPROVED** [review]

**Comment by tbirdso** [comment]
Thanks @thewtex and @dzenanz, I will be sure to bump external module versions when updating CI for new ITK tags in the future.

**Pull request merged**
